# common setting
spring:
  application:
    name: PurchaseService
  main:
    web-application-type: servlet
  docker:
    compose:
      enabled: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT:5000}
      repositories:
        enabled: false
      lettuce:
        pool:
          max-active: ${SPRING_DATA_REDIS_POOL_MAX_ACTIVE:8}
          max-idle: ${SPRING_DATA_REDIS_POOL_MAX_IDLE:8}
          min-idle: ${SPRING_DATA_REDIS_POOL_MIN_IDLE:0}
          max-wait: ${SPRING_DATA_REDIS_POOL_MAX_WAIT:-1ms}



logging:
  file:
    name: ./logs/purchase-service.log
  level:
    root: INFO
    org.java.purchaseservice: DEBUG

tickets:
  bootstrap:
    venue-redis: ${TICKETS_BOOTSTRAP_VENUE_REDIS:true}

sns:
  topic:
    ticket-created-arn: arn:aws:sns:us-west-2:123456789012:ticket.exchange.fifo